### ISSUE TITLE
'unsubscribe' of undefined

### ISSUE THREAD

**Issue by supachai24** [udayvunnam/xng-breadcrumb#122]
### Description
I got this error for angular ssr.

#### 💻Your Environment

**Angular Version: 8.2.3**

<pre><code>

## 🔥 Exception or Error
TypeError: Cannot read property 'unsubscribe' of undefined
    at BreadcrumbComponent.ngOnDestroy (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:121857:27)
    at callProviderLifecycles (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:80984:18)
    at callElementProvidersLifecycles (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:80943:13)
    at callLifecycleHooksChildrenFirst (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:80925:29)
    at destroyView (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:92025:5)
    at callViewAction (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:92184:13)
    at execComponentViewsAction (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:92092:13)
    at destroyView (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:92024:5)
    at callViewAction (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:92184:13)
    at execComponentViewsAction (/Users/miw03/Desktop/Angular/edt-2022/dist/server/main.js:92092:13)

<pre><code>

</code></pre>

**Comment by udayvunnam** [comment]
@supachai24 I have tried SSR in the latest version of xng-breadcrumb and it works w/out any issue. 

I have also added a demo app with usage in this repository for angular ssr - https://github.com/udayvunnam/xng-breadcrumb/tree/main/apps/ssr. you can run `yarn start:ssr` 

If you are still facing the issue, please provide a reusable example.
