### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by anyplin** [udayvunnam/xng-breadcrumb#132]
Upgrading to version >=v7.1.1 results in error posted below during unit tests. Anyone who can help me figure out what I need to do to make the test succeed? I am using Angular v13 and the unit tests which fail all use the breadcrumbService to set the label and logo for the specific component pages.
Thank you very much.

```
TypeError: Cannot read properties of undefined (reading 'routeConfig')
	    at BreadcrumbService.prepareBreadcrumbList (node_modules/xng-breadcrumb/fesm2015/xng-breadcrumb.mjs:113:42)
	    at BreadcrumbService.setupBreadcrumbs (node_modules/xng-breadcrumb/fesm2015/xng-breadcrumb.mjs:85:14)
	    at BreadcrumbService.detectRouteChanges (node_modules/xng-breadcrumb/fesm2015/xng-breadcrumb.mjs:68:14)
	    at new BreadcrumbService (node_modules/xng-breadcrumb/fesm2015/xng-breadcrumb.mjs:59:14)
	    at Object.BreadcrumbService_Factory [as factory] (node_modules/xng-breadcrumb/fesm2015/xng-breadcrumb.mjs:322:1)
	    at R3Injector.hydrate (node_modules/@angular/core/fesm2015/core.mjs:11457:1)
	    at R3Injector.get (node_modules/@angular/core/fesm2015/core.mjs:11276:1)
	    at NgModuleRef.get (node_modules/@angular/core/fesm2015/core.mjs:21840:1)
	    at Object.get (node_modules/@angular/core/fesm2015/core.mjs:21517:1)
	    at lookupTokenUsingModuleInjector (node_modules/@angular/core/fesm2015/core.mjs:3358:1)
```

**Comment by diego-bevilaqua86** [comment]
@anyplin I'm pretty new to this lib myself, but I think it would be easier to find the problem if you could create a reproduction scenario in a StackBlitz, so that we all have access to the environment and check the error that rises.

**Comment by udayvunnam** [comment]
@anyplin could you provide an example

**Comment by anyplin** [comment]
Hello, sorry I was not able to recreate an example but I managed to solve it by spying on the breadcrumbService in the affected tests.
